bar_height = 21
bar_opacity = 0.7008415460586548
font_size = 11.0
idle_display_off = 15
idle_suspend = 30
nightlight_end = 6
nightlight_mode = "scheduled"
nightlight_start = 19
nightlight_temp = 2500
taskbar_height = 21
